# This is a TOML document

# title
# tttttttttttttttt
title = "TOML Example"
# int1
int1 = 123456789
# long1
long1 = 1234567890000
# noop
noop = [{ a = 1, b = 2 }, { b = 2, c = 3 }]

[owner]
# name
name = "Tom Preston-Werner"
date = 2022-07-23
dob = 1979-05-27T07:32:00-08:00

[database]
enabled = true
points = [[1, 2, 3], [4, 5.5, 6], [7, 8, 99999999999999]]
ports = [8000, 8001, 8002]
data = [["delta", "phi"], [3.14]]
temp_targets = { cpu = 79.5, apu = 72.0 }

[servers]

# aaa
[servers.alpha]
ip = "10.0.0.1"
role = "frontend"

# bbb
[servers.beta]
ip = "10.0.0.2"
role = "backend"
